Added UAVOnix dialect from documentation.
botlink/go-mavlink pull request #2
Opened 2017-05-14 01:37 UTC by botBoss

NOTE: This does not match the published UAVonix.xml file provided by MAVLINK maintainers. That file is quite old.

2017-05-24 01:16 UTC, botBoss commented
@brandon-hass this is in support of ADS-B transponder support.  I added all the Uavionix messages to the UAVionix dialect.

Golint doesn't like the "self" parameter in the method definitions, but that matches the style of the  rest of the package.

2017-05-24 15:29 UTC, brandon-hass requested changes
I feel like for the sake of consistency, creating the .xml file to generate the code and then modifying the CRC_EXTRA manually (unless you can get the field names to calculate it correctly, which would be ideal) would make more sense. Thoughts?

2017-05-24 20:31 UTC, botBoss commented
If you'd prefer I can definitely do that; assuming that works, you want the enum values in the XML as well?

2017-05-24 20:35 UTC, botBoss commented
Although -- if we have to manually modify the XMLCrc after generation, doesn't that break the guarantee of the generated code being correct for subsequent users?

2017-05-24 20:47 UTC, botBoss commented
Disregard last comment.  Looks like documentation lists byte offsets so we should be GTG.

2017-05-25 01:32 UTC, botBoss commented
@brandon-hass Generated UAVionix dialect from the XML message set. CRCs needed to be manually changed because UAVionix doesn't actually give you the correct XML message name. I'm going to reach out and see if they will provide those.

2017-05-25 01:39 UTC, botBoss commented
@brandon-hass Also, it looks like the generator is producing incorrect output for the OWN_SHIP_STATIC message. The packing and unpacking functions seem to be incorrect. Any ideas/can you take a look?

2017-05-25 15:17 UTC, brandon-hass commented
@botBoss It looks like uAvionix isn't ordering their fields correctly (or at least in the same way the other dialects do), which is causing the output that you're seeing. I thought it was an issue with the generator at first, but that doesn't seem to be the case.

2017-05-25 15:19 UTC, brandon-hass commented on mavlink/definitions/uavionix.xml
> +      <enum name="UAVIONIX_SDA_LEVEL">
Since this is part of the uAvionix dialect, would there be a problem dropping the `UAVONIX_` prefix?

2017-05-25 15:24 UTC, botBoss commented on mavlink/definitions/uavionix.xml
> +      <enum name="UAVIONIX_SDA_LEVEL">
@brandon-hass I saw the other dialects doing prefixes like that, and the MAVLink common message set enums all start with MAVLink, so I thought that was the standard.

2017-05-25 15:26 UTC, botBoss commented on mavlink/definitions/uavionix.xml
> +      <enum name="UAVIONIX_SDA_LEVEL">
Well, OK, looking again at least the ualberta guys did :)

2017-05-25 15:27 UTC, brandon-hass commented on mavlink/definitions/uavionix.xml
> +      <enum name="UAVIONIX_SDA_LEVEL">
Ah, I see it in a few places. It just felt super verbose, but obviously doesn't matter.

2017-05-25 15:27 UTC, brandon-hass approved these changes

2017-05-25 15:29 UTC, botBoss commented on mavlink/definitions/uavionix.xml
> +      <enum name="UAVIONIX_SDA_LEVEL">
I agree, it's unfortunate that there aren't any real standards in any of these definition files (or MAVLink as a whole).

2017-05-25 15:29 UTC, merged